### ISSUE TITLE
fix bug where next image doesn't load on finalize annotations

### ISSUE THREAD

**Issue by rrjoson** [laguro-developers/swarmerai#97]

**Comment by joseliecast** [comment]
Hi @wleite  I was unsuccessful reproducing this bug, please add a detail step by step description.

**Comment by rrjoson** [comment]
@joseliecast 

Confirmed this bug with willian. 

First, you need to setup the project so that it uses classes and binary so that a job looks like this:

![image](https://user-images.githubusercontent.com/6985314/61101116-3fdf5d80-a49b-11e9-874a-b1ea7b8e48e7.png)

Then try finishing all the tasks in the job then you'll notice you never reaches this UI after the last task:

![image](https://user-images.githubusercontent.com/6985314/61101154-5d142c00-a49b-11e9-8fa0-c10526c86fa8.png)

**Comment by joseliecast** [comment]
Potential fix

https://github.com/laguro-developers/swarmerai/pull/119
