### ISSUE TITLE
Change deleteProject to stopProject

### ISSUE THREAD

**Issue by rrjoson** [laguro-developers/swarmerai#98]
### Notes
- Make necessary copy changes to match mutation change
- We shouldn't delete project because it would be a problem if the project has jobs connected to it

**Comment by rrjoson** [comment]
@jinlee8502 @laguro-sam 

Is this just a text change? Tried to look for an endProject mutation but can't find it in the repo.

**Comment by jinlee8502** [comment]
i just checked, and endProject changed to stopProject

**Comment by joseliecast** [comment]
Fix for review

https://github.com/laguro-developers/swarmerai/pull/115
